### ISSUE TITLE
 deferred error: AttributeError type object 'Script' has no attribute 'goto'

### ISSUE THREAD

**Issue by wqshi** [tkf/emacs-jedi#264]
The jedi for emacs was working perfectly, but recently it gives me the following error when I try to goto the definition of the function.

deferred error : (error "\"AttributeError(\\\"type object 'Script' has no attribute 'goto'\\\",)\""

I went through the trouble shooting part of the jedi document. Here are some results.

The  jedi:show-setup-info info is in https://gist.github.com/wqshi/286cb5f6b7a2e5c854ef.

The traceback is here.
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "/homed/home/shi/.emacs.d/.python-environments/default/lib/python2.7/site-packages/epc/handler.py", line 242, in _handle
    reply = handler(uid, *args)
  File "/homed/home/shi/.emacs.d/.python-environments/default/lib/python2.7/site-packages/epc/utils.py", line 51, in new_method
    ret = method(self, *args, **kwds)
  File "/homed/home/shi/.emacs.d/.python-environments/default/lib/python2.7/site-packages/epc/handler.py", line 265, in _handle_call
    return ['return', uid, func(*args)]
  File "/homed/home/shi/.local/lib/python2.7/site-packages/jediepcserver-0.0.0-py2.7.egg/jediepcserver.py", line 90, in get_in_function_call
    call_def = jedi_script(*args).get_in_function_call()
AttributeError: 'Script' object has no attribute 'get_in_function_call'

Any suggestions? Thanks in advance.

**Comment by syohex** [comment]
I suppose you use old jediepcserver.py. Please update. I fixed for newer Jedi API at https://github.com/tkf/emacs-jedi/commit/e4d365958586231c86a0686ca786077142ca92e7

**Comment by wqshi** [comment]
Thanks for your suggestion. I did try jedi:install-server in emacs before. But the problem is still there.
Finally I pip uninstall jediepcserver, and then redo the jedi:install-server. The problem is solved. jedi:install-server seems don't clean the old version. 

Thanks a lot! Now I can enjoy python and emacs!
